### PR TITLE
Sorting Algorithm

### PR DESCRIPTION
**Pull request by pritishaw1**

### CODE REVIEW

**Comment by AbraaoHonorio** [comment]
Hello man, thanks for contributing to the repository, but your code is in **_C_** and this repository is in _**C++**_.
Can you make this change?

**Comment by pritishaw1** [comment]
Hello,
Sure. I will make the changes required as soon as possible.
Thank you,
Priti

**Comment by AbraaoHonorio** [comment]
Thank you, I look forward to your new pull request.

**Comment by AbraaoHonorio** [comment]
@pritishaw1 hello man, any news about it? 
thanks!

**Comment by pritishaw1** [comment]
> @pritishaw1 hello man, any news about it?
> thanks!

Hi, 
I wanted to add the missing sorting algorithms to the repository. Back to the day when I created a pull request, I added the Merge sort algorithm in C. But when you pointed out the fact, that the repository maintains all the codes in C++, I noticed that you have already included the code for the Merge Sort technique in the file Sorting 01. So, I did not felt the need to add the same code, again. Hence, I'm closing the pull request, as of now.
Thank you!

**Pull request closed without merging**
